[package]
name = "koushin"
version = "0.2.0"
repository = "https://github.com/feefs/koushin"
description = "A CLI tool for quickly updating (更新) your currently watching MyAnimeList"
license = "MIT"
keywords = ["cli"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
chrono = "0.4.23"
clap = { version = "4.0.32", features = ["derive"] }
eyre = "0.6.8"
inquire = "0.5.2"
nanoid = "0.4.0"
open = "3.2.0"
owo-colors = "3.5.0"
phf = { version = "0.11.1", features = ["macros"] }
qstring = "0.7.2"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
spinners = "4.1.0"
termion = "2.0.1"
tiny_http = "0.12.0"
toml = "0.5.10"
ureq = { version = "2.6.1", features = ["json"] }

[build-dependencies]
clap = { version = "4.0.32", features = ["derive"] }
clap_complete = "4.0.7"
