[package]
name = "koushin"
version = "0.1.9"
edition = "2021"
description = "A CLI tool for quickly updating (更新) your currently watching MyAnimeList"

[dependencies]
chrono = "0.4.19"
clap = { version = "3.2.12", features = ["derive"] }
inquire = "0.2.1"
nanoid = "0.4.0"
open = "3.0.1"
owo-colors = "3.4.0"
phf = { version = "0.11.0", features = ["macros"] }
qstring = "0.7.2"
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
tiny_http = "0.11.0"
toml = "0.5.9"
ureq = {version = "2.5.0", features = ["json"] }
