[package]
name = "koushin"
version = "0.1.1"
edition = "2021"
description = "A CLI tool for quickly updating (更新) your episode count on MyAnimeList"

[dependencies]
chrono = "0.4.19"
clap = { version = "3.0.14", features = ["derive"] }
inquire = "0.2.1"
nanoid = "0.4.0"
owo-colors = "3.2.0"
qstring = "0.7.2"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tiny_http = "0.10.0"
toml = "0.5.8"
ureq = {version = "2.4.0", features = ["json"] }
