[package]
name = "koushin"
version = "0.3.1"
repository = "https://github.com/feefs/koushin"
description = "A CLI tool for quickly updating (更新) your currently watching MyAnimeList"
license = "MIT"
keywords = ["cli"]
categories = ["command-line-utilities"]
edition = "2024"

[dependencies]
ansi_term = "0.12.1"
chrono = "0.4.45"
clap = { version = "4.6.5", features = ["derive"] }
crossterm = "0.29.0"
eyre = "0.6.12"
inquire = "0.9.4"
nanoid = "0.5.0"
webbrowser = "1.2.2"
phf = { version = "0.14.0", features = ["macros"] }
qstring = "0.7.2"
serde = { version = "1.0.229", features = ["derive"] }
spinners = "4.2.0"
tiny_http = "0.12.0"
toml = "1.1.4"
ureq = { version = "3.3.0", features = ["json"] }
xdg = "3.0.0"

[build-dependencies]
clap = { version = "4.6.5", features = ["derive"] }
clap_complete = "4.6.8"

[lints.rust]
unused_crate_dependencies = "deny"
[lints.clippy]
cargo = "warn"
pedantic = "warn"
multiple_crate_versions = { level = "allow", priority = 1 }
