[package]
name = "koushin"
version = "0.1.15"
repository = "https://github.com/feefs/koushin"
description = "A CLI tool for quickly updating (更新) your currently watching MyAnimeList"
license = "MIT"
keywords = ["cli"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
chrono = "0.4.23"
clap = { version = "4.0.27", features = ["derive"] }
eyre = "0.6.8"
inquire = "0.4.0"
nanoid = "0.4.0"
open = "3.2.0"
owo-colors = "3.5.0"
phf = { version = "0.11.1", features = ["macros"] }
qstring = "0.7.2"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"
tiny_http = "0.11.0"
toml = "0.5.9"
ureq = { version = "2.5.0", features = ["json"] }

[build-dependencies]
clap = { version = "4.0.27", features = ["derive"] }
clap_complete = "4.0.6"
