name: Build

on:
  push:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: rustfmt
      run: cargo fmt --all -- --check

    - name: clippy
      run: cargo clippy -- -D warnings

    - name: build
      run: cargo build --release
